version: '3'
services:
  github-recomendations:
    container_name: github-recomendations
    build:
      context: ./GithubRecomendations
      dockerfile: ../Dockerfile
    volumes:
    - ./GithubRecomendations:/app/
    tty: true
    ports:
      - '5173:5173'
