version: '3'
services:
  github-recomendations:
    container_name: github-recomendations
    build:
      context: ./GithubRecomendations
      dockerfile: ../GithubRecomendations/Dockerfile
    volumes:
      - ./GithubRecomendations:/app/
    environment:
      - NODE_ENV=development
    ports:
      - '5173:5173'
    env_file:
      - .env

  github-recomendations-server:
    container_name: github-recomendations-server
    build:
      context: ./server
      dockerfile: ../server/Dockerfile
    volumes:
      - ./server:/app/
    environment:
      - NODE_ENV=development
    ports:
      - '8000:8000'
    env_file:
      - .env
