version: '3'
services:
  github-recomendations:
    container_name: github-recomendations
    build:
      context: ./GithubRecomendations
      dockerfile: ../Dockerfile
    volumes:
      - ./GithubRecomendations:/app/
    environment:
      - NODE_ENV=development
    tty: true
    entrypoint: npm run dev
    ports:
      - '5173:5173'
